import * as _deepl from './deepl';
import * as _bing from './bing';
import * as _yandex from './yandex';
import * as _openai from './openai';
import * as _google from './google';
import * as _transmart from './transmart';
import * as _alibaba from './alibaba';
import * as _baidu from './baidu';
import * as _baidu_field from './baidu_field';
import * as _tencent from './tencent';
import * as _volcengine from './volcengine';
import * as _niutrans from './niutrans';
import * as _youdao from './youdao';
import * as _bing_dict from './bing_dict';
import * as _cambridge_dict from './cambridge_dict';
import * as _caiyun from './caiyun';
import * as _chatglm from './chatglm';
import * as _geminipro from './geminipro';
import * as _ollama from './ollama';
import * as _ecdict from './ecdict';
import * as _lingva from './lingva';
import * as _openai_cloud from './openai_cloud';
import * as _gemini_cloud from './gemini_cloud';
import * as _claude_cloud from './claude_cloud';
import * as _chatglm_cloud from './chatglm_cloud';
import * as _moonshot_cloud from './moonshot_cloud';
import * as _minimax_cloud from './minimax_cloud';
import * as _deepseek_cloud from './deepseek_cloud';
import * as _tongyi_cloud from './tongyi_cloud';

export const deepl = _deepl;
export const bing = _bing;
export const yandex = _yandex;
export const openai = _openai;
export const google = _google;
export const transmart = _transmart;
export const alibaba = _alibaba;
export const baidu = _baidu;
export const baidu_field = _baidu_field;
export const tencent = _tencent;
export const volcengine = _volcengine;
export const niutrans = _niutrans;
export const youdao = _youdao;
export const bing_dict = _bing_dict;
export const cambridge_dict = _cambridge_dict;
export const caiyun = _caiyun;
export const chatglm = _chatglm;
export const geminipro = _geminipro;
export const ollama = _ollama;
export const ecdict = _ecdict;
export const lingva = _lingva;
export const openai_cloud = _openai_cloud;
export const gemini_cloud = _gemini_cloud;
export const claude_cloud = _claude_cloud;
export const chatglm_cloud = _chatglm_cloud;
export const moonshot_cloud = _moonshot_cloud;
export const minimax_cloud = _minimax_cloud;
export const deepseek_cloud = _deepseek_cloud;
export const tongyi_cloud = _tongyi_cloud;
